package simulation

import (
	"math/rand"

	"sync-engine/internal/crdt"
)

// recordedOp pairs a generated operation with the ID of the client that generated it
type recordedOp struct {
	op        crdt.Operation
	generator uint64
}

// dependsOn returns the OperationID a given operation requires to have
// already been applied to a replica before it can be applied itself, or nil if there is no such requirement.
// For InsertOperation, this is the parent element's identifier
// For DeleteOperation, this is always nil
func dependsOn(op crdt.Operation) *crdt.OperationID {
	ins, ok := op.(crdt.InsertOperation)
	if !ok {
		return nil
	}
	if ins.ParentElementID.IsRoot() {
		return nil
	}
	dep := crdt.OperationID(ins.ParentElementID)
	return &dep
}

// deliveryPlan produces a randomized, causally-valid delivery order for one target client
func deliveryPlan(rng *rand.Rand, targetClientID uint64, allOps []recordedOp, duplicateProbability float64) []crdt.Operation {
	// Node set: every operation not generated by the target.
	nodes := make(map[crdt.OperationID]recordedOp, len(allOps))
	for _, r := range allOps {
		if r.generator == targetClientID {
			continue
		}
		nodes[r.op.ID()] = r
	}

	// in-degree and reverse adjacency, considering only edges whose
	// dependency is itself a node in this target's graph.
	inDegree := make(map[crdt.OperationID]int, len(nodes))
	dependents := make(map[crdt.OperationID][]crdt.OperationID)
	for id, r := range nodes {
		dep := dependsOn(r.op)
		if dep == nil {
			continue
		}
		if _, depIsNode := nodes[*dep]; depIsNode {
			inDegree[id]++
			dependents[*dep] = append(dependents[*dep], id)
		}
	}

	var ready []crdt.OperationID
	for id := range nodes {
		if inDegree[id] == 0 {
			ready = append(ready, id)
		}
	}

	order := make([]crdt.Operation, 0, len(nodes))
	for len(ready) > 0 {
		i := rng.Intn(len(ready))
		id := ready[i]
		ready[i] = ready[len(ready)-1]
		ready = ready[:len(ready)-1]

		order = append(order, nodes[id].op)

		for _, dependent := range dependents[id] {
			inDegree[dependent]--
			if inDegree[dependent] == 0 {
				ready = append(ready, dependent)
			}
		}
		if rng.Float64() < duplicateProbability {
			order = append(order, nodes[id].op)
		}
	}
	return order
}
