package simulation

import (
	"math/rand"
	"testing"

	"sync-engine/internal/crdt"
)

func chainInsert(clientID, counter uint64, parent crdt.ElementID, value rune) crdt.InsertOperation {
	id := crdt.Identifier{ClientID: clientID, Counter: counter}
	return crdt.InsertOperation{
		OperationID:     crdt.OperationID(id),
		DocumentID:      "doc",
		ClientID:        clientID,
		LogicalClock:    counter,
		ParentElementID: parent,
		ElementID:       crdt.ElementID(id),
		Value:           value,
	}
}

func TestDeliveryPlan_ExcludesSelfGeneratedOperations(t *testing.T) {
	op := chainInsert(5, 1, crdt.ElementID(crdt.RootID), 'a')
	ops := []recordedOp{{op: op, generator: 5}}

	rng := rand.New(rand.NewSource(1))
	order := deliveryPlan(rng, 5, ops, 0)

	if len(order) != 0 {
		t.Fatalf("expected target's own operations to be excluded, got %v", order)
	}
}

func TestDeliveryPlan_IncludesOthersOperations(t *testing.T) {
	op := chainInsert(5, 1, crdt.ElementID(crdt.RootID), 'a')
	ops := []recordedOp{{op: op, generator: 5}}

	rng := rand.New(rand.NewSource(1))
	order := deliveryPlan(rng, 9, ops, 0)

	if len(order) != 1 {
		t.Fatalf("expected 1 delivered operation for a different target, got %d", len(order))
	}
}

// TestDeliveryPlan_RespectsParentDependency builds a three-link causal
// chain (a <- b <- c, each the next one's parent) generated by one
// client, and verifies that across many random trials, deliveryPlan
// never places b before a or c before b for a different target client.
// This is the property the whole simulator depends on: random delivery
// orders that are still causally valid.
func TestDeliveryPlan_RespectsParentDependency(t *testing.T) {
	a := chainInsert(1, 1, crdt.ElementID(crdt.RootID), 'a')
	b := chainInsert(1, 2, a.ElementID, 'b')
	c := chainInsert(1, 3, b.ElementID, 'c')

	ops := []recordedOp{
		{op: c, generator: 1}, // deliberately out of causal order in the input slice
		{op: a, generator: 1},
		{op: b, generator: 1},
	}

	rng := rand.New(rand.NewSource(1))
	for trial := 0; trial < 2000; trial++ {
		order := deliveryPlan(rng, 2, ops, 0)
		if len(order) != 3 {
			t.Fatalf("trial %d: expected 3 operations in delivery order, got %d", trial, len(order))
		}

		posA, posB, posC := -1, -1, -1
		for i, op := range order {
			switch op.(crdt.InsertOperation).ElementID {
			case a.ElementID:
				posA = i
			case b.ElementID:
				posB = i
			case c.ElementID:
				posC = i
			}
		}

		if posA == -1 || posB == -1 || posC == -1 {
			t.Fatalf("trial %d: missing operation in delivery order: %v", trial, order)
		}
		if posA > posB || posB > posC {
			t.Fatalf("trial %d: dependency violated (want a<b<c): posA=%d posB=%d posC=%d, order=%v",
				trial, posA, posB, posC, order)
		}
	}
}

// TestDeliveryPlan_ConcurrentSiblingsCanLandInEitherOrder checks the
// flip side: two operations with NO dependency relationship between them
// (siblings of the same parent, generated by different clients) should,
// across many trials, actually be observed in both relative orders --
// confirming the randomization isn't accidentally over-constrained into
// always producing the same linearization.
func TestDeliveryPlan_ConcurrentSiblingsCanLandInEitherOrder(t *testing.T) {
	root := crdt.ElementID(crdt.RootID)
	x := chainInsert(2, 1, root, 'X')
	y := chainInsert(3, 1, root, 'Y')
	ops := []recordedOp{
		{op: x, generator: 2},
		{op: y, generator: 3},
	}

	rng := rand.New(rand.NewSource(1))
	sawXFirst, sawYFirst := false, false
	for trial := 0; trial < 200; trial++ {
		order := deliveryPlan(rng, 9, ops, 0)
		if order[0].(crdt.InsertOperation).ElementID == x.ElementID {
			sawXFirst = true
		} else {
			sawYFirst = true
		}
	}

	if !sawXFirst || !sawYFirst {
		t.Errorf("expected both relative orderings to occur across 200 trials, sawXFirst=%v sawYFirst=%v",
			sawXFirst, sawYFirst)
	}
}

func TestDeliveryPlan_DuplicateProbabilityOne_DuplicatesEveryOperation(t *testing.T) {
	a := chainInsert(1, 1, crdt.ElementID(crdt.RootID), 'a')
	ops := []recordedOp{{op: a, generator: 1}}

	rng := rand.New(rand.NewSource(1))
	order := deliveryPlan(rng, 2, ops, 1.0)

	if len(order) != 2 {
		t.Fatalf("expected 2 deliveries (1 original + 1 duplicate) with duplicateProbability=1.0, got %d: %v",
			len(order), order)
	}
	for _, op := range order {
		if op.(crdt.InsertOperation).ElementID != a.ElementID {
			t.Errorf("expected both deliveries to be the same operation, got %v", order)
		}
	}
}

func TestDeliveryPlan_DuplicateProbabilityZero_NeverDuplicates(t *testing.T) {
	a := chainInsert(1, 1, crdt.ElementID(crdt.RootID), 'a')
	b := chainInsert(1, 2, a.ElementID, 'b')
	ops := []recordedOp{{op: a, generator: 1}, {op: b, generator: 1}}

	rng := rand.New(rand.NewSource(1))
	for trial := 0; trial < 500; trial++ {
		order := deliveryPlan(rng, 2, ops, 0)
		if len(order) != 2 {
			t.Fatalf("trial %d: expected exactly 2 deliveries with duplicateProbability=0, got %d: %v",
				trial, len(order), order)
		}
	}
}
